version: "3.8"

services:
  app:
    image: heydolono/smit-test:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
      - sqlite_data:/app/db
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"


volumes:
  sqlite_data:
